// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../gir-files
// DO NOT EDIT

use glib::translate::*;

use crate::ffi;

glib::wrapper! {
    #[doc(alias = "WebKitFavicon")]
    pub struct Favicon(Object<ffi::WebKitFavicon, ffi::WebKitFaviconClass>);

    match fn {
        type_ => || ffi::webkit_favicon_get_type(),
    }
}

impl Favicon {
    #[doc(alias = "webkit_favicon_get_bytes")]
    #[doc(alias = "get_bytes")]
    pub fn bytes(&self) -> Option<glib::Bytes> {
        unsafe { from_glib_none(ffi::webkit_favicon_get_bytes(self.to_glib_none().0)) }
    }

    #[doc(alias = "webkit_favicon_get_height")]
    #[doc(alias = "get_height")]
    pub fn height(&self) -> i32 {
        unsafe { ffi::webkit_favicon_get_height(self.to_glib_none().0) }
    }

    #[doc(alias = "webkit_favicon_get_width")]
    #[doc(alias = "get_width")]
    pub fn width(&self) -> i32 {
        unsafe { ffi::webkit_favicon_get_width(self.to_glib_none().0) }
    }
}
