// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../gir-files
// DO NOT EDIT

use glib::prelude::*;
use glib::translate::*;

use crate::ffi;

glib::wrapper! {
    #[doc(alias = "WebKitImage")]
    pub struct Image(Object<ffi::WebKitImage, ffi::WebKitImageClass>);

    match fn {
        type_ => || ffi::webkit_image_get_type(),
    }
}

impl Image {
    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`Image`]
    /// objects.
    ///
    /// This method returns an instance of
    /// [`ImageBuilder`](crate::builders::ImageBuilder) which can be used to
    /// create [`Image`] objects.
    pub fn builder() -> ImageBuilder {
        ImageBuilder::new()
    }

    #[doc(alias = "webkit_image_as_bytes")]
    pub fn as_bytes(&self) -> Option<glib::Bytes> {
        unsafe { from_glib_none(ffi::webkit_image_as_bytes(self.to_glib_none().0)) }
    }

    #[doc(alias = "webkit_image_get_height")]
    #[doc(alias = "get_height")]
    pub fn height(&self) -> i32 {
        unsafe { ffi::webkit_image_get_height(self.to_glib_none().0) }
    }

    #[doc(alias = "webkit_image_get_stride")]
    #[doc(alias = "get_stride")]
    pub fn stride(&self) -> u32 {
        unsafe { ffi::webkit_image_get_stride(self.to_glib_none().0) }
    }

    #[doc(alias = "webkit_image_get_width")]
    #[doc(alias = "get_width")]
    pub fn width(&self) -> i32 {
        unsafe { ffi::webkit_image_get_width(self.to_glib_none().0) }
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`Image`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct ImageBuilder {
    builder: glib::object::ObjectBuilder<'static, Image>,
}

impl ImageBuilder {
    fn new() -> Self {
        Self { builder: glib::object::Object::builder() }
    }

    pub fn height(self, height: i32) -> Self {
        Self { builder: self.builder.property("height", height) }
    }

    pub fn stride(self, stride: u32) -> Self {
        Self { builder: self.builder.property("stride", stride) }
    }

    pub fn width(self, width: i32) -> Self {
        Self { builder: self.builder.property("width", width) }
    }

    // rustdoc-stripper-ignore-next
    /// Build the [`Image`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to \
                  have side effects"]
    pub fn build(self) -> Image {
        self.builder.build()
    }
}
