// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../gir-files
// DO NOT EDIT

use crate::PermissionRequest;

glib::wrapper! {
    #[doc(alias = "WebKitMediaKeySystemPermissionRequest")]
    pub struct MediaKeySystemPermissionRequest(Object<ffi::WebKitMediaKeySystemPermissionRequest, ffi::WebKitMediaKeySystemPermissionRequestClass>) @implements PermissionRequest;

    match fn {
        type_ => || ffi::webkit_media_key_system_permission_request_get_type(),
    }
}

impl MediaKeySystemPermissionRequest {}
