// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../gir-files
// DO NOT EDIT

mod authentication_request;
pub use self::authentication_request::AuthenticationRequest;

mod automation_session;
pub use self::automation_session::AutomationSession;

mod back_forward_list;
pub use self::back_forward_list::BackForwardList;

mod back_forward_list_item;
pub use self::back_forward_list_item::BackForwardListItem;

mod context_menu;
pub use self::context_menu::ContextMenu;

mod context_menu_item;
pub use self::context_menu_item::ContextMenuItem;

mod cookie_manager;
pub use self::cookie_manager::CookieManager;

mod device_info_permission_request;
pub use self::device_info_permission_request::DeviceInfoPermissionRequest;

mod download;
pub use self::download::Download;

mod editor_state;
pub use self::editor_state::EditorState;

mod file_chooser_request;
pub use self::file_chooser_request::FileChooserRequest;

mod find_controller;
pub use self::find_controller::FindController;

mod form_submission_request;
pub use self::form_submission_request::FormSubmissionRequest;

mod geolocation_manager;
pub use self::geolocation_manager::GeolocationManager;

mod geolocation_permission_request;
pub use self::geolocation_permission_request::GeolocationPermissionRequest;

mod hit_test_result;
pub use self::hit_test_result::HitTestResult;

mod input_method_context;
pub use self::input_method_context::InputMethodContext;

mod media_key_system_permission_request;
pub use self::media_key_system_permission_request::MediaKeySystemPermissionRequest;

mod navigation_policy_decision;
pub use self::navigation_policy_decision::NavigationPolicyDecision;

mod network_session;
pub use self::network_session::NetworkSession;

mod notification;
pub use self::notification::Notification;

mod notification_permission_request;
pub use self::notification_permission_request::NotificationPermissionRequest;

mod option_menu;
pub use self::option_menu::OptionMenu;

mod permission_request;
pub use self::permission_request::PermissionRequest;

mod policy_decision;
pub use self::policy_decision::PolicyDecision;

mod response_policy_decision;
pub use self::response_policy_decision::ResponsePolicyDecision;

mod security_manager;
pub use self::security_manager::SecurityManager;

mod settings;
pub use self::settings::Settings;

mod uri_request;
pub use self::uri_request::URIRequest;

mod uri_response;
pub use self::uri_response::URIResponse;

mod uri_scheme_request;
pub use self::uri_scheme_request::URISchemeRequest;

mod uri_scheme_response;
pub use self::uri_scheme_response::URISchemeResponse;

mod user_content_filter_store;
pub use self::user_content_filter_store::UserContentFilterStore;

mod user_content_manager;
pub use self::user_content_manager::UserContentManager;

mod user_media_permission_request;
pub use self::user_media_permission_request::UserMediaPermissionRequest;

mod user_message;
pub use self::user_message::UserMessage;

mod web_context;
pub use self::web_context::WebContext;

mod web_resource;
pub use self::web_resource::WebResource;

mod web_view;
pub use self::web_view::WebView;

mod website_data_access_permission_request;
pub use self::website_data_access_permission_request::WebsiteDataAccessPermissionRequest;

mod website_data_manager;
pub use self::website_data_manager::WebsiteDataManager;

mod website_policies;
pub use self::website_policies::WebsitePolicies;

mod window_properties;
pub use self::window_properties::WindowProperties;

mod application_info;
pub use self::application_info::ApplicationInfo;

mod color;
pub use self::color::Color;

mod credential;
pub use self::credential::Credential;

mod feature;
pub use self::feature::Feature;

mod feature_list;
pub use self::feature_list::FeatureList;

mod geolocation_position;
pub use self::geolocation_position::GeolocationPosition;

mod itp_first_party;
pub use self::itp_first_party::ITPFirstParty;

mod itp_third_party;
pub use self::itp_third_party::ITPThirdParty;

mod input_method_underline;
pub use self::input_method_underline::InputMethodUnderline;

mod memory_pressure_settings;
pub use self::memory_pressure_settings::MemoryPressureSettings;

mod navigation_action;
pub use self::navigation_action::NavigationAction;

mod network_proxy_settings;
pub use self::network_proxy_settings::NetworkProxySettings;

mod option_menu_item;
pub use self::option_menu_item::OptionMenuItem;

mod permission_state_query;
pub use self::permission_state_query::PermissionStateQuery;

mod rectangle;
pub use self::rectangle::Rectangle;

mod script_dialog;
pub use self::script_dialog::ScriptDialog;

mod script_message_reply;
pub use self::script_message_reply::ScriptMessageReply;

mod security_origin;
pub use self::security_origin::SecurityOrigin;

mod user_content_filter;
pub use self::user_content_filter::UserContentFilter;

mod user_script;
pub use self::user_script::UserScript;

mod user_style_sheet;
pub use self::user_style_sheet::UserStyleSheet;

mod web_view_backend;
pub use self::web_view_backend::WebViewBackend;

mod web_view_session_state;
pub use self::web_view_session_state::WebViewSessionState;

mod website_data;
pub use self::website_data::WebsiteData;

mod enums;
pub use self::enums::{
    AuthenticationScheme, AutomationBrowsingContextPresentation, AutoplayPolicy, CacheModel,
    ContextMenuAction, CookieAcceptPolicy, CookiePersistentStorage, CredentialPersistence,
    DownloadError, FeatureStatus, InputPurpose, InsecureContentEvent, JavascriptError, LoadEvent,
    MediaCaptureState, MediaError, NavigationType, NetworkError, NetworkProxyMode, PermissionState,
    PolicyDecisionType, PolicyError, SaveMode, ScriptDialogType, SnapshotError, TLSErrorsPolicy,
    UserContentFilterError, UserContentInjectedFrames, UserMessageError, UserScriptInjectionTime,
    UserStyleLevel, WebExtensionMode, WebProcessTerminationReason,
};

mod flags;
pub use self::flags::{
    EditorTypingAttributes, FindOptions, HitTestResultContext, InputHints, WebsiteDataTypes,
};

pub(crate) mod traits {
    pub use super::input_method_context::InputMethodContextExt;
    pub use super::permission_request::PermissionRequestExt;
    pub use super::policy_decision::PolicyDecisionExt;
    pub use super::web_view::WebViewExt;
}
pub(crate) mod builders {
    pub use super::automation_session::AutomationSessionBuilder;
    pub use super::download::DownloadBuilder;
    pub use super::find_controller::FindControllerBuilder;
    pub use super::hit_test_result::HitTestResultBuilder;
    pub use super::network_session::NetworkSessionBuilder;
    pub use super::settings::SettingsBuilder;
    pub use super::uri_request::URIRequestBuilder;
    pub use super::uri_scheme_response::URISchemeResponseBuilder;
    pub use super::user_content_filter_store::UserContentFilterStoreBuilder;
    pub use super::user_message::UserMessageBuilder;
    pub use super::web_context::WebContextBuilder;
    pub use super::web_view::WebViewBuilder;
    pub use super::website_data_manager::WebsiteDataManagerBuilder;
    pub use super::website_policies::WebsitePoliciesBuilder;
    pub use super::window_properties::WindowPropertiesBuilder;
}
