// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../gir-files
// DO NOT EDIT

use crate::{ffi, PermissionRequest};

glib::wrapper! {
    #[doc(alias = "WebKitNotificationPermissionRequest")]
    pub struct NotificationPermissionRequest(Object<ffi::WebKitNotificationPermissionRequest, ffi::WebKitNotificationPermissionRequestClass>) @implements PermissionRequest;

    match fn {
        type_ => || ffi::webkit_notification_permission_request_get_type(),
    }
}

impl NotificationPermissionRequest {}
