[options]
library = "WPEPlatform"
version = "2.0"
min_cfg_version = "2.0"
target_path = "."
girs_directories = ["/usr/share/gir-1.0/", "../gir-files"]
work_mode = "normal"
single_version_file = true
deprecate_by_min_version = true
generate_builder = true
generate = [
    "WPEPlatform.AvailableInputDevices",
    "WPEPlatform.Buffer",
    "WPEPlatform.BufferDMABufFormats",
    "WPEPlatform.BufferDMABufFormatsBuilder",
    "WPEPlatform.BufferDMABufFormatUsage",
    "WPEPlatform.BufferError",
    "WPEPlatform.BufferSHM",
    "WPEPlatform.Clipboard",
    "WPEPlatform.ClipboardContent",
    "WPEPlatform.Color",
    "WPEPlatform.Display",
    "WPEPlatform.DisplayError",
    "WPEPlatform.DRMDevice",
    "WPEPlatform.EGLError",
    "WPEPlatform.Event",
    "WPEPlatform.EventType",
    "WPEPlatform.Gamepad",
    "WPEPlatform.GamepadAxis",
    "WPEPlatform.GamepadButton",
    "WPEPlatform.GamepadManager",
    "WPEPlatform.Gesture",
    "WPEPlatform.GestureController",
    "WPEPlatform.InputHints",
    "WPEPlatform.InputMethodContext",
    "WPEPlatform.InputMethodUnderline",
    "WPEPlatform.InputPurpose",
    "WPEPlatform.InputSource",
    "WPEPlatform.Keymap",
    #"WPEPlatform.KeymapEntry",
    "WPEPlatform.KeymapXKB",
    "WPEPlatform.Modifiers",
    "WPEPlatform.Monitor",
    "WPEPlatform.PixelFormat",
    "WPEPlatform.Rectangle",
    "WPEPlatform.Screen",
    "WPEPlatform.ScreenSyncObserver",
    "WPEPlatform.Settings",
    "WPEPlatform.SettingsError",
    "WPEPlatform.SettingsHintingStyle",
    "WPEPlatform.SettingsSource",
    "WPEPlatform.SettingsSubpixelLayout",
    "WPEPlatform.Toplevel",
    "WPEPlatform.ToplevelState",
    "WPEPlatform.ViewAccessible",
    "WPEPlatform.ViewError",
]

manual = [
    "Gio.OutputStream",
    "GLib.Bytes",
    "GLib.DestroyNotify",
    "GLib.Error",
    "GLib.KeyFile",
    "GLib.Variant",
    "GLib.VariantType",
]

[[object]]
name = "WPEPlatform.View"
status = "generate"
function = [
    { name = "set_opaque_rectangles", manual = true },
    { name = "render_buffer", manual = true },
]

[[object]]
name = "WPEPlatform.BufferDMABuf"
status = "generate"
function = [
    { name = "new", manual = true },
]
