[options]
library = "WPEWebKit"
version = "2.0"
min_cfg_version = "2.45"
target_path = "."
girs_directories = ["/usr/share/gir-1.0/", "../gir-files"]
work_mode = "sys"
single_version_file = true
external_libraries = [
    "GLib",
    "GObject",
    "Gio",
    "wpe",
    "Soup",
    "WPEJavaScriptCore",
    "WPEPlatform",
]
