// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../gir-files
// DO NOT EDIT

use glib::translate::*;

use crate::{BufferFormatUsage, BufferFormats, DRMDevice, ffi};

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct BufferFormatsBuilder(Shared<ffi::WPEBufferFormatsBuilder>);

    match fn {
        ref => |ptr| ffi::wpe_buffer_formats_builder_ref(ptr),
        unref => |ptr| ffi::wpe_buffer_formats_builder_unref(ptr),
        type_ => || ffi::wpe_buffer_formats_builder_get_type(),
    }
}

impl BufferFormatsBuilder {
    #[doc(alias = "wpe_buffer_formats_builder_new")]
    pub fn new(device: Option<&DRMDevice>) -> BufferFormatsBuilder {
        unsafe { from_glib_full(ffi::wpe_buffer_formats_builder_new(device.to_glib_none().0)) }
    }

    #[doc(alias = "wpe_buffer_formats_builder_append_format")]
    pub fn append_format(&self, fourcc: u32, modifier: u64) {
        unsafe {
            ffi::wpe_buffer_formats_builder_append_format(self.to_glib_none().0, fourcc, modifier);
        }
    }

    #[doc(alias = "wpe_buffer_formats_builder_append_group")]
    pub fn append_group(&self, device: Option<&DRMDevice>, usage: BufferFormatUsage) {
        unsafe {
            ffi::wpe_buffer_formats_builder_append_group(
                self.to_glib_none().0,
                device.to_glib_none().0,
                usage.into_glib(),
            );
        }
    }

    #[doc(alias = "wpe_buffer_formats_builder_end")]
    pub fn end(self) -> Option<BufferFormats> {
        unsafe { from_glib_full(ffi::wpe_buffer_formats_builder_end(self.into_glib_ptr())) }
    }
}
