// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "WPEBuffer", sizeof(WPEBuffer), alignof(WPEBuffer));
    printf("%s;%zu;%zu\n", "WPEBufferClass", sizeof(WPEBufferClass), alignof(WPEBufferClass));
    printf("%s;%zu;%zu\n", "WPEBufferDMABufClass", sizeof(WPEBufferDMABufClass), alignof(WPEBufferDMABufClass));
    printf("%s;%zu;%zu\n", "WPEBufferDMABufFormatUsage", sizeof(WPEBufferDMABufFormatUsage), alignof(WPEBufferDMABufFormatUsage));
    printf("%s;%zu;%zu\n", "WPEBufferDMABufFormatsClass", sizeof(WPEBufferDMABufFormatsClass), alignof(WPEBufferDMABufFormatsClass));
    printf("%s;%zu;%zu\n", "WPEBufferError", sizeof(WPEBufferError), alignof(WPEBufferError));
    printf("%s;%zu;%zu\n", "WPEBufferSHMClass", sizeof(WPEBufferSHMClass), alignof(WPEBufferSHMClass));
    printf("%s;%zu;%zu\n", "WPEColor", sizeof(WPEColor), alignof(WPEColor));
    printf("%s;%zu;%zu\n", "WPEDisplay", sizeof(WPEDisplay), alignof(WPEDisplay));
    printf("%s;%zu;%zu\n", "WPEDisplayClass", sizeof(WPEDisplayClass), alignof(WPEDisplayClass));
    printf("%s;%zu;%zu\n", "WPEDisplayError", sizeof(WPEDisplayError), alignof(WPEDisplayError));
    printf("%s;%zu;%zu\n", "WPEEGLError", sizeof(WPEEGLError), alignof(WPEEGLError));
    printf("%s;%zu;%zu\n", "WPEEventType", sizeof(WPEEventType), alignof(WPEEventType));
    printf("%s;%zu;%zu\n", "WPEGesture", sizeof(WPEGesture), alignof(WPEGesture));
    printf("%s;%zu;%zu\n", "WPEGestureControllerInterface", sizeof(WPEGestureControllerInterface), alignof(WPEGestureControllerInterface));
    printf("%s;%zu;%zu\n", "WPEInputHints", sizeof(WPEInputHints), alignof(WPEInputHints));
    printf("%s;%zu;%zu\n", "WPEInputMethodContext", sizeof(WPEInputMethodContext), alignof(WPEInputMethodContext));
    printf("%s;%zu;%zu\n", "WPEInputMethodContextClass", sizeof(WPEInputMethodContextClass), alignof(WPEInputMethodContextClass));
    printf("%s;%zu;%zu\n", "WPEInputPurpose", sizeof(WPEInputPurpose), alignof(WPEInputPurpose));
    printf("%s;%zu;%zu\n", "WPEInputSource", sizeof(WPEInputSource), alignof(WPEInputSource));
    printf("%s;%zu;%zu\n", "WPEKeymap", sizeof(WPEKeymap), alignof(WPEKeymap));
    printf("%s;%zu;%zu\n", "WPEKeymapClass", sizeof(WPEKeymapClass), alignof(WPEKeymapClass));
    printf("%s;%zu;%zu\n", "WPEKeymapEntry", sizeof(WPEKeymapEntry), alignof(WPEKeymapEntry));
    printf("%s;%zu;%zu\n", "WPEKeymapXKBClass", sizeof(WPEKeymapXKBClass), alignof(WPEKeymapXKBClass));
    printf("%s;%zu;%zu\n", "WPEModifiers", sizeof(WPEModifiers), alignof(WPEModifiers));
    printf("%s;%zu;%zu\n", "WPEMonitor", sizeof(WPEMonitor), alignof(WPEMonitor));
    printf("%s;%zu;%zu\n", "WPEMonitorClass", sizeof(WPEMonitorClass), alignof(WPEMonitorClass));
    printf("%s;%zu;%zu\n", "WPEPixelFormat", sizeof(WPEPixelFormat), alignof(WPEPixelFormat));
    printf("%s;%zu;%zu\n", "WPERectangle", sizeof(WPERectangle), alignof(WPERectangle));
    printf("%s;%zu;%zu\n", "WPEToplevel", sizeof(WPEToplevel), alignof(WPEToplevel));
    printf("%s;%zu;%zu\n", "WPEToplevelClass", sizeof(WPEToplevelClass), alignof(WPEToplevelClass));
    printf("%s;%zu;%zu\n", "WPEToplevelState", sizeof(WPEToplevelState), alignof(WPEToplevelState));
    printf("%s;%zu;%zu\n", "WPEView", sizeof(WPEView), alignof(WPEView));
    printf("%s;%zu;%zu\n", "WPEViewClass", sizeof(WPEViewClass), alignof(WPEViewClass));
    printf("%s;%zu;%zu\n", "WPEViewError", sizeof(WPEViewError), alignof(WPEViewError));
    return 0;
}
